// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYD8inNjcbHXn2uRwlIimmOfxfd9egFDw',
    appId: '1:509704591066:web:535e12f5a3e739fc3037e3',
    messagingSenderId: '509704591066',
    projectId: 'chatlive-fc70b',
    authDomain: 'chatlive-fc70b.firebaseapp.com',
    storageBucket: 'chatlive-fc70b.firebasestorage.app',
    measurementId: 'G-3TM9426MRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GaEHlIzuIuXY6SvQOt42OVOCmAs7TuY',
    appId: '1:509704591066:android:5911eb41bc35d7ef3037e3',
    messagingSenderId: '509704591066',
    projectId: 'chatlive-fc70b',
    storageBucket: 'chatlive-fc70b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvPMHTc3GjtYuQVW8r0IKRiuHaie08we8',
    appId: '1:509704591066:ios:e21ae214f0cdea413037e3',
    messagingSenderId: '509704591066',
    projectId: 'chatlive-fc70b',
    storageBucket: 'chatlive-fc70b.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvPMHTc3GjtYuQVW8r0IKRiuHaie08we8',
    appId: '1:509704591066:ios:e21ae214f0cdea413037e3',
    messagingSenderId: '509704591066',
    projectId: 'chatlive-fc70b',
    storageBucket: 'chatlive-fc70b.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYD8inNjcbHXn2uRwlIimmOfxfd9egFDw',
    appId: '1:509704591066:web:4c640a62157d19193037e3',
    messagingSenderId: '509704591066',
    projectId: 'chatlive-fc70b',
    authDomain: 'chatlive-fc70b.firebaseapp.com',
    storageBucket: 'chatlive-fc70b.firebasestorage.app',
    measurementId: 'G-YC5V5FXCE9',
  );
}
